message(STATUS "Configuring Vulkan-Headers...")

set(VULKAN_HEADERS_ENABLE_MODULE OFF)

FetchContent_Declare(Vulkan-Headers
	GIT_REPOSITORY https://github.com/KhronosGroup/Vulkan-Headers
	GIT_TAG e3b1eec08173d6b825cd3ac88c885a63b621504a # vulkan-sdk-1.4.357.0
	EXCLUDE_FROM_ALL
	SYSTEM
	OVERRIDE_FIND_PACKAGE)

FetchContent_MakeAvailable(Vulkan-Headers)

set(GREM_GRAPHICS_PRIVATE_DEPENDENCIES ${GREM_GRAPHICS_PRIVATE_DEPENDENCIES} Vulkan-Headers PARENT_SCOPE)

set(VULKAN_HEADERS_INSTALL_DIR ${vulkan-headers_SOURCE_DIR} PARENT_SCOPE) # Needed by volk.

file(READ "${vulkan-headers_SOURCE_DIR}/LICENSES/Apache-2.0.txt" GREM_VULKAN_HEADERS_APACHE_LICENSE_FILE_CONTENTS)
string(REPLACE "\r\n" "\n" GREM_VULKAN_HEADERS_APACHE_LICENSE_FILE_CONTENTS "${GREM_VULKAN_HEADERS_APACHE_LICENSE_FILE_CONTENTS}")

file(READ "${vulkan-headers_SOURCE_DIR}/LICENSES/MIT.txt" GREM_VULKAN_HEADERS_MIT_LICENSE_FILE_CONTENTS)
string(REPLACE "\r\n" "\n" GREM_VULKAN_HEADERS_MIT_LICENSE_FILE_CONTENTS "${GREM_VULKAN_HEADERS_MIT_LICENSE_FILE_CONTENTS}")

set(GREM_VULKAN_HEADERS_TITLE "Vulkan-Headers (vulkan-sdk-1.4.357.0)" PARENT_SCOPE)
set(GREM_VULKAN_HEADERS_USE "Used by GREM, volk and Vulkan Memory Allocator." PARENT_SCOPE)
set(GREM_VULKAN_HEADERS_LINK "https://github.com/KhronosGroup/Vulkan-Headers/tree/e3b1eec08173d6b825cd3ac88c885a63b621504a" PARENT_SCOPE)
set(GREM_VULKAN_HEADERS_COPYRIGHT "Copyright 2015-2023 The Khronos Group Inc." PARENT_SCOPE)
set(GREM_VULKAN_HEADERS_LICENSES "${GREM_VULKAN_HEADERS_APACHE_LICENSE_FILE_CONTENTS}```\n\n```\n${GREM_VULKAN_HEADERS_MIT_LICENSE_FILE_CONTENTS}" PARENT_SCOPE)

set(GREM_DEPENDENCY_PREFIXES ${GREM_DEPENDENCY_PREFIXES}
	GREM_VULKAN_HEADERS
	PARENT_SCOPE)
