// SPDX-FileCopyrightText: 2026 Ivar Härnqvist
// SPDX-License-Identifier: MIT

#ifndef GREM_GRAPHICS_3D_OPENGL_BUILTIN_SHADERS_GRAPHICS_3D_STUB_HPP
#define GREM_GRAPHICS_3D_OPENGL_BUILTIN_SHADERS_GRAPHICS_3D_STUB_HPP

#include <GREM/build_config.hpp>

#include <GREM/core/data/CStringView.hpp>

namespace grem::graphics {

namespace detail {

inline constexpr CStringView CUBEMAP_3D_DEFAULT_VERTEX_SHADER_CODE{};
inline constexpr CStringView LIGHT_BAKER_3D_CUBEMAP_IRRADIANCE_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView LIGHT_BAKER_3D_CUBEMAP_REFLECTION_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView LIGHT_BAKER_3D_CUBEMAP_FROM_EQUIRECTANGULAR_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView LIGHT_BAKER_3D_LIGHT_PROBE_ATLAS_DEFAULT_VERTEX_SHADER_CODE{};
inline constexpr CStringView LIGHT_BAKER_3D_LIGHT_PROBE_ATLAS_IRRADIANCE_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView LIGHT_BAKER_3D_LIGHT_PROBE_ATLAS_DISTANCE_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_SPECULAR_SPLIT_SUM_BRDF_INTEGRATION_MAP_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_DEFAULT_SKY_3D_VERTEX_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_PBR_SKY_3D_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_DEFAULT_MODEL_3D_VERTEX_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_UNLIT_MODEL_3D_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_PBR_MODEL_3D_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_SHADOW_MAP_MODEL_3D_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_DISTANCE_MODEL_3D_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_DEFAULT_MODEL_2D_TRANSFORMED_3D_VERTEX_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_PLAIN_MODEL_2D_TRANSFORMED_3D_FRAGMENT_SHADER_CODE{};
inline constexpr CStringView RENDERER_3D_TEXT_MODEL_2D_TRANSFORMED_3D_FRAGMENT_SHADER_CODE{};

} // namespace detail

} // namespace grem::graphics

#endif
