set(CMAKE_SYSTEM_NAME Windows CACHE STRING "" FORCE)

set(CMAKE_SYSTEM_PROCESSOR x86_64 CACHE STRING "" FORCE)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++ CACHE STRING "" FORCE)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-w64-mingw32" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE STRING "" FORCE)

set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM "windows+pe" CACHE STRING "" FORCE)
