message(STATUS "Configuring volk...")

FetchContent_Declare(volk
	GIT_REPOSITORY https://github.com/zeux/volk
	GIT_TAG 776893306c5d3b22b6185b5d4a258b81d94572bf # vulkan-sdk-1.4.357.0
	EXCLUDE_FROM_ALL
	SYSTEM)

FetchContent_MakeAvailable(volk)

set(GREM_GRAPHICS_PRIVATE_DEPENDENCIES ${GREM_GRAPHICS_PRIVATE_DEPENDENCIES} volk PARENT_SCOPE)

file(READ "${volk_SOURCE_DIR}/LICENSE.md" GREM_VOLK_LICENSE_FILE_CONTENTS)
string(REPLACE "\r\n" "\n" GREM_VOLK_LICENSE_FILE_CONTENTS "${GREM_VOLK_LICENSE_FILE_CONTENTS}")
string(REGEX MATCH "Copyright \\(c\\) 2018-.... Arseny Kapoulkine" GREM_VOLK_COPYRIGHT_FILE_CONTENTS "${GREM_VOLK_LICENSE_FILE_CONTENTS}")

set(GREM_VOLK_TITLE "volk (vulkan-sdk-1.4.357.0)" PARENT_SCOPE)
set(GREM_VOLK_USE "Used by GREM, and indirectly by Vulkan Memory Allocator as used by GREM." PARENT_SCOPE)
set(GREM_VOLK_LINK "https://github.com/zeux/volk/tree/776893306c5d3b22b6185b5d4a258b81d94572bf" PARENT_SCOPE)
set(GREM_VOLK_COPYRIGHT "${GREM_VOLK_COPYRIGHT_FILE_CONTENTS}" PARENT_SCOPE)
set(GREM_VOLK_LICENSE "${GREM_VOLK_LICENSE_FILE_CONTENTS}" PARENT_SCOPE)

set(GREM_DEPENDENCY_PREFIXES ${GREM_DEPENDENCY_PREFIXES}
	GREM_VOLK
	PARENT_SCOPE)
