message(STATUS "Configuring SPIRV-Headers...")

FetchContent_Declare(SPIRV-Headers
	GIT_REPOSITORY https://github.com/KhronosGroup/SPIRV-Headers
	GIT_TAG 29981f65241605e08b0ede4cfeb999fe3b723c6a # vulkan-sdk-1.4.357.0
	EXCLUDE_FROM_ALL
	SYSTEM
	OVERRIDE_FIND_PACKAGE)

FetchContent_MakeAvailable(SPIRV-Headers)

file(READ "${spirv-headers_SOURCE_DIR}/LICENSE" GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS)
string(REPLACE "\r\n" "\n" GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS "${GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS}")
string(REGEX MATCH "Files: All files except for those called out below\\.\n(Copyright \\(c\\) 2015-.... The Khronos Group Inc\\.[^-]*DEALINGS IN THE MATERIALS\\.\n)" GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS "${GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS}")
set(GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS "${CMAKE_MATCH_1}")
string(SUBSTRING "${GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS}" 0 46 GREM_SPIRV_HEADERS_COPYRIGHT_FILE_CONTENTS)

file(READ "${spirv-headers_SOURCE_DIR}/LICENSE" GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS)
string(REPLACE "\r\n" "\n" GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS "${GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS}")
string(REGEX MATCH "Files: include/spirv/spir-v\\.xml\n(Copyright \\(c\\) 2015-.... The Khronos Group Inc\\..*DEALINGS IN THE MATERIALS\\.\n)" GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS "${GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS}")
set(GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS "${CMAKE_MATCH_1}")
string(SUBSTRING "${GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS}" 0 46 GREM_SPIRV_HEADERS_SPIRV_XML_COPYRIGHT_FILE_CONTENTS)

set(GREM_SPIRV_HEADERS_TITLE "SPIRV-Headers (vulkan-sdk-1.4.357.0)" PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_USE "Used by SPIRV-Tools." PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_LINK "https://github.com/KhronosGroup/SPIRV-Headers/tree/29981f65241605e08b0ede4cfeb999fe3b723c6a" PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_COPYRIGHT "${GREM_SPIRV_HEADERS_COPYRIGHT_FILE_CONTENTS}" PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_LICENSE "${GREM_SPIRV_HEADERS_LICENSE_FILE_CONTENTS}" PARENT_SCOPE)

set(GREM_SPIRV_HEADERS_SPIRV_XML_TITLE "include/spirv/spir-v.xml" PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_SPIRV_XML_USE "Part of SPIRV-Headers." PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_SPIRV_XML_LINK "https://github.com/KhronosGroup/SPIRV-Headers/blob/29981f65241605e08b0ede4cfeb999fe3b723c6a/include/spirv/spir-v.xml" PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_SPIRV_XML_COPYRIGHT "${GREM_SPIRV_HEADERS_SPIRV_XML_COPYRIGHT_FILE_CONTENTS}" PARENT_SCOPE)
set(GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE "${GREM_SPIRV_HEADERS_SPIRV_XML_LICENSE_FILE_CONTENTS}" PARENT_SCOPE)

set(GREM_DEPENDENCY_PREFIXES ${GREM_DEPENDENCY_PREFIXES}
	GREM_SPIRV_HEADERS
	GREM_SPIRV_HEADERS_SPIRV_XML
	PARENT_SCOPE)
