name: Generate Documentation Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Emscripten SDK
        uses: emscripten-core/setup-emsdk@v16

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Configure
        run: cmake --preset emscripten-release

      - name: Build
        run: cmake --build --preset emscripten-release -DGREM_BUILD_DOCS=ON

      - name: Install
        run: cmake --install build/emscripten-release

      - name: Generate Documentation
        run: cmake --build build/emscripten-release --target GREM-generate-documentation

      - name: Copy Examples
        run: cp -r build/emscripten-release/install/bin build/emscripten-release/docs/html

      - name: Create .nojekyll file
        run: touch build/emscripten-release/docs/html/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/emscripten-release/docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
